name: NuGet Publish
on:
  push:
    branches:
    - master
    paths:
    - '!README.md'
    - 'LICENSE'
    - 'EnhancedConsole.ApplicationTemplate/Content/*'
jobs:
  publish:
    name: Build, Pack, & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.300

      # Publish
      - name: Publish NuGet On Version Change 
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: EnhancedConsole.ApplicationTemplate/Content/EnhancedConsole.ApplicationTemplate.csproj
          
          PACKAGE_NAME: TH.Utilities.EnhancedConsoleApplication

          VERSION_REGEX: <PackageVersion>(.*)<\/PackageVersion>

          TAG_COMMIT: true

          TAG_FORMAT: v*

          NUGET_KEY: ${{secrets.NUGET_API_KEY}}